### ISSUE TITLE
open words.txt: no such file or directory

### ISSUE THREAD

**Issue by TechComSpot** [mikemadden42/s3buster#1]
Hi, I try to run the tool but got an error:

open words.txt: no such file or directory

Can you advice, please?
![Screenshot_2020-09-06-13-53-32-183_com termux](https://user-images.githubusercontent.com/9653037/92324234-83eed380-f048-11ea-91e5-a383f844e5ff.jpg)

**Comment by mikemadden42** [comment]
Hi @r3mb00 ; the text file `words.txt` needs to be in your current working directory.

```
$ go get -u -ldflags "-s -w" github.com/mikemadden42/s3buster

$ cd $HOME/go/src/github.com/mikemadden42/s3buster

$ s3buster
library-videos.s3-us-west-1.amazonaws.com
52.219.112.73
52.219.112.105
52.219.116.89
52.219.120.153
key: AAK__SC_6-28-1997_Maritime_Hall_short.mp4, size: 44709975
key: AAK_in_Hawaii.mp4, size: 46787695
key: Khansahib_Alam_2002.mp4, size: 39625019
key: Mike_Malone_interview_1991short.mp4, size: 46722329
key: Spirit_of_the_Sarode.mp4, size: 69106391
key: Swiss_documentary_short.mp4, size: 52907137
....
....
```

Please let me know if you have any further questions.

**Comment by TechComSpot** [comment]
Thank you for your response, but it still doesn't work :

**Comment by TechComSpot** [comment]
There is not mikemadden42 directory. :(

**Comment by mikemadden42** [comment]
Interesting...  I have a couple quick questions:

1. Where did you clone the `s3buster` repo?  The `words.txt` file is included as a sample and is in the top-level directory of the repo (https://github.com/mikemadden42/s3buster/blob/master/words.txt).
2. The `go get` command I included earlier should have checked out the repo and put it under `$GOPATH/src/github.com/mikemadden42/s3buster`.  Maybe your `$GOPATH` is different than mine?

**Comment by mikemadden42** [comment]
The sample `words.txt` file can be downloaded from the following location and placed in a location of your choice.

https://raw.githubusercontent.com/mikemadden42/s3buster/master/words.txt

**Comment by TechComSpot** [comment]
Here is my $GOPATH :

**Comment by TechComSpot** [comment]
It's weird because others go tools I have installed are located in src/
github.com/...etc
but not yours one :(

**Comment by mikemadden42** [comment]
That is odd.  I would recommend creating a `words.txt` file in a directory of your choice.  You could start with the same buckets I have in my sample `words.txt`.

```
$ cat $HOME/go/src/github.com/mikemadden42/s3buster/words.txt
library-videos
opendns-downloads
screenshots.test
cdb
ut-webassets
```

**Comment by mikemadden42** [comment]
The `words.txt` included in the repo is a sample.  You'll want to configure your own local `words.txt` to meet your requirements.
